import type { Metadata } from "next";
import { Antonio, Bebas_Neue, Fahkwang, Geist, Geist_Mono, Pathway_Gothic_One, Poppins } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const antonio = Antonio({
  weight: "100",         
  variable: "--font-antonio",
  subsets: ["latin"],
});

const fahkwang = Fahkwang({
  weight: "200",         
  variable: "--font-fahkwang",
  subsets: ["latin"],
});

const bebas = Bebas_Neue({
  weight: "400",         
  variable: "--font-bebas-neue",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}  ${fahkwang.variable} ${geistMono.variable} ${bebas.variable}  ${antonio.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
